name: URL
on:
  workflow_dispatch:
jobs:
  generate-url:
    uses: ./.github/workflows/Generate_URL.yaml
    with:
      NAME: "SHANKAR...!!!"
          # instance: "mprod01"
          # service_name: "credit-card"
          # URL: "https://artifactory"