name: My First Workflow

on: 
  # push:
  workflow_dispatch: 

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name : Welcome Message
              run: echo "Welcome to my first workflow learning"

            - name: Listings
              run: |
                ls
                echo ${{ github.workspace }}
            
            - name: Read the file
              run: cat README.md
            - name: Dump GitHub context
              env:
                GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"
        
