name: My First Workflow

on: 
  push:
  workflow_dispatch: 
  pull_request:
    branches:
        - main
    types:
        - closed
        - opened

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name : Welcome Message
              run: echo "Welcome to my first workflow learning"

            - name: Listings
              run: |
                ls
                echo ${{ github.workspace }}
            
            - name: Read the file
              run: cat README.md
            - name: Dump GitHub context
              env:
                GITHUB_CONTEXT: ${{ toJson(github) }}
              run: |
                echo "$GITHUB_CONTEXT"
                pull_request_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
                echo $pull_request_number
                echo $GITHUB_EVENT_PATH
        
