name: Generate URL
on:
  workflow_dispatch:
    inputs:
      DK_ID:
        description: "Enter dk****"
        required: true
      instance:
        description: "enter mprod, prod1"
        required: true
      service_name:
        description: "example credit-card-service-v2"
        required: true
      URL:
        description: "Artifactory URL"
        required: true
    outputs:
      application-url:
        value: ${{ jobs.generate-url.outputs.APP_URL }}
jobs:
  generate-url:
    runs-on: ubuntu-latest
    outputs:
      APP_URL: ${{ steps.set-url.outputs.APP_URL }}
    steps:
      - name: Generate the URL
        id: set-url
        run: |
          echo "APP_URL=$(https://portal.dap.intranet.db.com/action/run/?id=${{ inputs.DK_ID}}&instance=${{ inputs.instance}}&action=helm&verb=upgrade&arguments=-i%20${{ inputs.service_name }}-keystore%20hlm-all/bsl-certstore%20--valuesurl%20${{inputs.URL}})" >> "$GITHUB_OUTPUT"
          echo "$APP_URL"