name: Generate URL
on:
  workflow_dispatch
    inputs:
      ID:
        description: "Enter dk****"
        required: true
      instance:
        description: "enter mprod, prod1"
        required: true
      service_name:
        description: "example credit-card-service-v2"
        required: true
      URL:
        description: "Artifactory URL"
        required: true
jobs:
  Generate URL:
    runs-on: ubuntu-latest
    outputs:
      APP_URL: ${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
    steps:
      - name: Generate the URL
        id: set-url
        run: echo "APP_URL=https://portal.dap.intranet.db.com/action/run/?id=${{ inputs.ID}}&instance=${{ inputs.instance}}&action=helm&verb=upgrade&arguments=-i%20${{ inputs.service_name }}-keystore%20hlm-all/bsl-certstore%20--valuesurl%20${{inputs.URL}}" >> "$GITHUB_OUTPUT"