name: Matrix
on:
    # push: 
    workflow_dispatch: 
jobs:
    Matrix-Job:
      strategy:
  # If any steps fails then the it will cancel the other running jobs also if the value is true
          fail-fast: false
    # This will define how many jobs should run in paralell      
          max-parallel: 2
          matrix:
              os: [ubuntu-latest, ubuntu-20.4, windows-latest]
              image: [hello-world, alpine]
              exclude:
                  - image: alpine
                    os: windows-latest
      runs-on: ${{ matrix.os }}
      steps:
      - name: Echo Docker 
        run: docker info

      - name: Run docker on ${{ matrix.os }}
        run: docker run ${{ matrix.image }}