name: Variables
on: workflow_dispatch
  # push
# Workflow level
# env:
#     USERNAME: Shankar
#     PASSWORD: Shankar
#     DOCKER_REPO: docker.io
# jobs:
#     build:
#         runs-on: ubuntu-latest
#         steps:
#         - name: Docker build
#           run: echo docker build -t ${{ env.DOCKER_REPO }}/$USERNAME/nginx:latest

#         - name: Docker Login
#           run: echo docker login --username=${{ env.USERNAME }} --password=$PASSWORD

# Repo level
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Docker build
          run: echo docker build -t ${{ vars.DOCKER_REPO }}/${{ vars.USERNAME }}/nginx:latest

        - name: Docker Login
          run: echo docker login --username=${{ vars.USERNAME }} --password=${{ secrets.PASSWORD }}
    
     
    deploy:
        # This field is added to create dependeny with the previous job and run only after the 
        # successful run of previous job
        needs: build
        # Following will be added to queue the newly created workflow and start 
        # it once the previous work flow is completed
        concurrency: 
          cancel-in-progress: true
        # Following parameter will be added in Minutes to timeoput the workflow and cancel it
        # if it takes beyond the mentioned values.  
        timeout-minutes: 1
        runs-on: ubuntu-latest
        steps:
        - name: Push
          run: |
            echo docker push
            sleep 600s